#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import config
from cdetails.cdetails import create_app
from werkzeug.serving import run_simple

run_simple('0.0.0.0', 4580, create_app(config.config), use_debugger=False, use_reloader=True)
